# Generated by Django 4.0 on 2021-12-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('localidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('nome_contato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.contato')),
            ],
        ),
    ]
