# Generated by Django 4.0 on 2021-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
